version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: AgendamentoDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 11111
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./backend
    depends_on:
      - db
    environment:
      ASPNETCORE_URLS: http://+:5000
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=AgendamentoDb;Username=postgres;Password=11111
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    depends_on:
      - api
    ports:
      - "8000:80"

volumes:
  pgdata:
